/// Flutter icons LocalIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LocalIcons
///      fonts:
///       - asset: fonts/LocalIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LocalIcons {
  LocalIcons._();

  static const _kFontFam = 'LocalIcons';

  static const IconData menu = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData my_profile = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData student = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData timetable = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData attendance = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData complaints = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData examination = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData fee_payment = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData grades = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe80c, fontFamily: _kFontFam);
}
